version: 2
updates:
  - package-ecosystem: "vcpkg"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      boost:
        patterns:
          - "boost-*"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # https://github.com/dependabot/dependabot-core/issues/6345#issuecomment-3376986288
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
