/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "remote_controller_constants.h"

namespace hazelcast { namespace client { namespace test { namespace remote {

const remote_controllerConstants g_remote_controller_constants;

remote_controllerConstants::remote_controllerConstants() {
}

}}}} // namespace

