/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "remote-controller_constants.h"



const remote-controllerConstants g_remote-controller_constants;

remote-controllerConstants::remote-controllerConstants() {
}



