/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef remote_controller_CONSTANTS_H
#define remote_controller_CONSTANTS_H

#include "remote_controller_types.h"

namespace hazelcast {
namespace client {
namespace test {
namespace remote {

class remote_controllerConstants
{
public:
    remote_controllerConstants();
};

extern const remote_controllerConstants g_remote_controller_constants;

} // namespace remote
} // namespace test
} // namespace client
} // namespace hazelcast

#endif
