/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef remote-controller_CONSTANTS_H
#define remote-controller_CONSTANTS_H

#include "remote-controller_types.h"



class remote-controllerConstants {
 public:
  remote-controllerConstants();

};

extern const remote-controllerConstants g_remote-controller_constants;



#endif
