/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef remotecontroller_CONSTANTS_H
#define remotecontroller_CONSTANTS_H

#include "remotecontroller_types.h"



class remotecontrollerConstants {
 public:
  remotecontrollerConstants();

};

extern const remotecontrollerConstants g_remotecontroller_constants;



#endif
