/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RemoteController_H
#define RemoteController_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "remotecontroller_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class RemoteControllerIf {
 public:
  virtual ~RemoteControllerIf() {}
  virtual bool ping() = 0;
  virtual bool clean() = 0;
  virtual bool exit() = 0;
  virtual void createCluster(Cluster& _return, const std::string& hzVersion, const std::string& xmlconfig) = 0;
  virtual void startMember(Member& _return, const std::string& clusterId) = 0;
  virtual bool shutdownMember(const std::string& clusterId, const std::string& memberId) = 0;
  virtual bool terminateMember(const std::string& clusterId, const std::string& memberId) = 0;
  virtual bool suspendMember(const std::string& clusterId, const std::string& memberId) = 0;
  virtual bool resumeMember(const std::string& clusterId, const std::string& memberId) = 0;
  virtual bool shutdownCluster(const std::string& clusterId) = 0;
  virtual bool terminateCluster(const std::string& clusterId) = 0;
  virtual void splitMemberFromCluster(Cluster& _return, const std::string& memberId) = 0;
  virtual void mergeMemberToCluster(Cluster& _return, const std::string& clusterId, const std::string& memberId) = 0;
  virtual void executeOnController(Response& _return, const std::string& clusterId, const std::string& script, const Lang::type lang) = 0;
};

class RemoteControllerIfFactory {
 public:
  typedef RemoteControllerIf Handler;

  virtual ~RemoteControllerIfFactory() {}

  virtual RemoteControllerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RemoteControllerIf* /* handler */) = 0;
};

class RemoteControllerIfSingletonFactory : virtual public RemoteControllerIfFactory {
 public:
  RemoteControllerIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<RemoteControllerIf>& iface) : iface_(iface) {}
  virtual ~RemoteControllerIfSingletonFactory() {}

  virtual RemoteControllerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RemoteControllerIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<RemoteControllerIf> iface_;
};

class RemoteControllerNull : virtual public RemoteControllerIf {
 public:
  virtual ~RemoteControllerNull() {}
  bool ping() {
    bool _return = false;
    return _return;
  }
  bool clean() {
    bool _return = false;
    return _return;
  }
  bool exit() {
    bool _return = false;
    return _return;
  }
  void createCluster(Cluster& /* _return */, const std::string& /* hzVersion */, const std::string& /* xmlconfig */) {
    return;
  }
  void startMember(Member& /* _return */, const std::string& /* clusterId */) {
    return;
  }
  bool shutdownMember(const std::string& /* clusterId */, const std::string& /* memberId */) {
    bool _return = false;
    return _return;
  }
  bool terminateMember(const std::string& /* clusterId */, const std::string& /* memberId */) {
    bool _return = false;
    return _return;
  }
  bool suspendMember(const std::string& /* clusterId */, const std::string& /* memberId */) {
    bool _return = false;
    return _return;
  }
  bool resumeMember(const std::string& /* clusterId */, const std::string& /* memberId */) {
    bool _return = false;
    return _return;
  }
  bool shutdownCluster(const std::string& /* clusterId */) {
    bool _return = false;
    return _return;
  }
  bool terminateCluster(const std::string& /* clusterId */) {
    bool _return = false;
    return _return;
  }
  void splitMemberFromCluster(Cluster& /* _return */, const std::string& /* memberId */) {
    return;
  }
  void mergeMemberToCluster(Cluster& /* _return */, const std::string& /* clusterId */, const std::string& /* memberId */) {
    return;
  }
  void executeOnController(Response& /* _return */, const std::string& /* clusterId */, const std::string& /* script */, const Lang::type /* lang */) {
    return;
  }
};


class RemoteController_ping_args {
 public:

  RemoteController_ping_args(const RemoteController_ping_args&);
  RemoteController_ping_args& operator=(const RemoteController_ping_args&);
  RemoteController_ping_args() {
  }

  virtual ~RemoteController_ping_args() throw();

  bool operator == (const RemoteController_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RemoteController_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_ping_pargs {
 public:


  virtual ~RemoteController_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_ping_result__isset {
  _RemoteController_ping_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_ping_result__isset;

class RemoteController_ping_result {
 public:

  RemoteController_ping_result(const RemoteController_ping_result&);
  RemoteController_ping_result& operator=(const RemoteController_ping_result&);
  RemoteController_ping_result() : success(0) {
  }

  virtual ~RemoteController_ping_result() throw();
  bool success;

  _RemoteController_ping_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_ping_presult__isset {
  _RemoteController_ping_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_ping_presult__isset;

class RemoteController_ping_presult {
 public:


  virtual ~RemoteController_ping_presult() throw();
  bool* success;

  _RemoteController_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class RemoteController_clean_args {
 public:

  RemoteController_clean_args(const RemoteController_clean_args&);
  RemoteController_clean_args& operator=(const RemoteController_clean_args&);
  RemoteController_clean_args() {
  }

  virtual ~RemoteController_clean_args() throw();

  bool operator == (const RemoteController_clean_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RemoteController_clean_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_clean_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_clean_pargs {
 public:


  virtual ~RemoteController_clean_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_clean_result__isset {
  _RemoteController_clean_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_clean_result__isset;

class RemoteController_clean_result {
 public:

  RemoteController_clean_result(const RemoteController_clean_result&);
  RemoteController_clean_result& operator=(const RemoteController_clean_result&);
  RemoteController_clean_result() : success(0) {
  }

  virtual ~RemoteController_clean_result() throw();
  bool success;

  _RemoteController_clean_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_clean_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_clean_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_clean_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_clean_presult__isset {
  _RemoteController_clean_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_clean_presult__isset;

class RemoteController_clean_presult {
 public:


  virtual ~RemoteController_clean_presult() throw();
  bool* success;

  _RemoteController_clean_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class RemoteController_exit_args {
 public:

  RemoteController_exit_args(const RemoteController_exit_args&);
  RemoteController_exit_args& operator=(const RemoteController_exit_args&);
  RemoteController_exit_args() {
  }

  virtual ~RemoteController_exit_args() throw();

  bool operator == (const RemoteController_exit_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RemoteController_exit_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_exit_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_exit_pargs {
 public:


  virtual ~RemoteController_exit_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_exit_result__isset {
  _RemoteController_exit_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_exit_result__isset;

class RemoteController_exit_result {
 public:

  RemoteController_exit_result(const RemoteController_exit_result&);
  RemoteController_exit_result& operator=(const RemoteController_exit_result&);
  RemoteController_exit_result() : success(0) {
  }

  virtual ~RemoteController_exit_result() throw();
  bool success;

  _RemoteController_exit_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_exit_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_exit_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_exit_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_exit_presult__isset {
  _RemoteController_exit_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_exit_presult__isset;

class RemoteController_exit_presult {
 public:


  virtual ~RemoteController_exit_presult() throw();
  bool* success;

  _RemoteController_exit_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_createCluster_args__isset {
  _RemoteController_createCluster_args__isset() : hzVersion(false), xmlconfig(false) {}
  bool hzVersion :1;
  bool xmlconfig :1;
} _RemoteController_createCluster_args__isset;

class RemoteController_createCluster_args {
 public:

  RemoteController_createCluster_args(const RemoteController_createCluster_args&);
  RemoteController_createCluster_args& operator=(const RemoteController_createCluster_args&);
  RemoteController_createCluster_args() : hzVersion(), xmlconfig() {
  }

  virtual ~RemoteController_createCluster_args() throw();
  std::string hzVersion;
  std::string xmlconfig;

  _RemoteController_createCluster_args__isset __isset;

  void __set_hzVersion(const std::string& val);

  void __set_xmlconfig(const std::string& val);

  bool operator == (const RemoteController_createCluster_args & rhs) const
  {
    if (!(hzVersion == rhs.hzVersion))
      return false;
    if (!(xmlconfig == rhs.xmlconfig))
      return false;
    return true;
  }
  bool operator != (const RemoteController_createCluster_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_createCluster_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_createCluster_pargs {
 public:


  virtual ~RemoteController_createCluster_pargs() throw();
  const std::string* hzVersion;
  const std::string* xmlconfig;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_createCluster_result__isset {
  _RemoteController_createCluster_result__isset() : success(false), serverException(false) {}
  bool success :1;
  bool serverException :1;
} _RemoteController_createCluster_result__isset;

class RemoteController_createCluster_result {
 public:

  RemoteController_createCluster_result(const RemoteController_createCluster_result&);
  RemoteController_createCluster_result& operator=(const RemoteController_createCluster_result&);
  RemoteController_createCluster_result() {
  }

  virtual ~RemoteController_createCluster_result() throw();
  Cluster success;
  ServerException serverException;

  _RemoteController_createCluster_result__isset __isset;

  void __set_success(const Cluster& val);

  void __set_serverException(const ServerException& val);

  bool operator == (const RemoteController_createCluster_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(serverException == rhs.serverException))
      return false;
    return true;
  }
  bool operator != (const RemoteController_createCluster_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_createCluster_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_createCluster_presult__isset {
  _RemoteController_createCluster_presult__isset() : success(false), serverException(false) {}
  bool success :1;
  bool serverException :1;
} _RemoteController_createCluster_presult__isset;

class RemoteController_createCluster_presult {
 public:


  virtual ~RemoteController_createCluster_presult() throw();
  Cluster* success;
  ServerException serverException;

  _RemoteController_createCluster_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_startMember_args__isset {
  _RemoteController_startMember_args__isset() : clusterId(false) {}
  bool clusterId :1;
} _RemoteController_startMember_args__isset;

class RemoteController_startMember_args {
 public:

  RemoteController_startMember_args(const RemoteController_startMember_args&);
  RemoteController_startMember_args& operator=(const RemoteController_startMember_args&);
  RemoteController_startMember_args() : clusterId() {
  }

  virtual ~RemoteController_startMember_args() throw();
  std::string clusterId;

  _RemoteController_startMember_args__isset __isset;

  void __set_clusterId(const std::string& val);

  bool operator == (const RemoteController_startMember_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_startMember_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_startMember_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_startMember_pargs {
 public:


  virtual ~RemoteController_startMember_pargs() throw();
  const std::string* clusterId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_startMember_result__isset {
  _RemoteController_startMember_result__isset() : success(false), serverException(false) {}
  bool success :1;
  bool serverException :1;
} _RemoteController_startMember_result__isset;

class RemoteController_startMember_result {
 public:

  RemoteController_startMember_result(const RemoteController_startMember_result&);
  RemoteController_startMember_result& operator=(const RemoteController_startMember_result&);
  RemoteController_startMember_result() {
  }

  virtual ~RemoteController_startMember_result() throw();
  Member success;
  ServerException serverException;

  _RemoteController_startMember_result__isset __isset;

  void __set_success(const Member& val);

  void __set_serverException(const ServerException& val);

  bool operator == (const RemoteController_startMember_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(serverException == rhs.serverException))
      return false;
    return true;
  }
  bool operator != (const RemoteController_startMember_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_startMember_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_startMember_presult__isset {
  _RemoteController_startMember_presult__isset() : success(false), serverException(false) {}
  bool success :1;
  bool serverException :1;
} _RemoteController_startMember_presult__isset;

class RemoteController_startMember_presult {
 public:


  virtual ~RemoteController_startMember_presult() throw();
  Member* success;
  ServerException serverException;

  _RemoteController_startMember_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_shutdownMember_args__isset {
  _RemoteController_shutdownMember_args__isset() : clusterId(false), memberId(false) {}
  bool clusterId :1;
  bool memberId :1;
} _RemoteController_shutdownMember_args__isset;

class RemoteController_shutdownMember_args {
 public:

  RemoteController_shutdownMember_args(const RemoteController_shutdownMember_args&);
  RemoteController_shutdownMember_args& operator=(const RemoteController_shutdownMember_args&);
  RemoteController_shutdownMember_args() : clusterId(), memberId() {
  }

  virtual ~RemoteController_shutdownMember_args() throw();
  std::string clusterId;
  std::string memberId;

  _RemoteController_shutdownMember_args__isset __isset;

  void __set_clusterId(const std::string& val);

  void __set_memberId(const std::string& val);

  bool operator == (const RemoteController_shutdownMember_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    if (!(memberId == rhs.memberId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_shutdownMember_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_shutdownMember_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_shutdownMember_pargs {
 public:


  virtual ~RemoteController_shutdownMember_pargs() throw();
  const std::string* clusterId;
  const std::string* memberId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_shutdownMember_result__isset {
  _RemoteController_shutdownMember_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_shutdownMember_result__isset;

class RemoteController_shutdownMember_result {
 public:

  RemoteController_shutdownMember_result(const RemoteController_shutdownMember_result&);
  RemoteController_shutdownMember_result& operator=(const RemoteController_shutdownMember_result&);
  RemoteController_shutdownMember_result() : success(0) {
  }

  virtual ~RemoteController_shutdownMember_result() throw();
  bool success;

  _RemoteController_shutdownMember_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_shutdownMember_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_shutdownMember_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_shutdownMember_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_shutdownMember_presult__isset {
  _RemoteController_shutdownMember_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_shutdownMember_presult__isset;

class RemoteController_shutdownMember_presult {
 public:


  virtual ~RemoteController_shutdownMember_presult() throw();
  bool* success;

  _RemoteController_shutdownMember_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_terminateMember_args__isset {
  _RemoteController_terminateMember_args__isset() : clusterId(false), memberId(false) {}
  bool clusterId :1;
  bool memberId :1;
} _RemoteController_terminateMember_args__isset;

class RemoteController_terminateMember_args {
 public:

  RemoteController_terminateMember_args(const RemoteController_terminateMember_args&);
  RemoteController_terminateMember_args& operator=(const RemoteController_terminateMember_args&);
  RemoteController_terminateMember_args() : clusterId(), memberId() {
  }

  virtual ~RemoteController_terminateMember_args() throw();
  std::string clusterId;
  std::string memberId;

  _RemoteController_terminateMember_args__isset __isset;

  void __set_clusterId(const std::string& val);

  void __set_memberId(const std::string& val);

  bool operator == (const RemoteController_terminateMember_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    if (!(memberId == rhs.memberId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_terminateMember_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_terminateMember_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_terminateMember_pargs {
 public:


  virtual ~RemoteController_terminateMember_pargs() throw();
  const std::string* clusterId;
  const std::string* memberId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_terminateMember_result__isset {
  _RemoteController_terminateMember_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_terminateMember_result__isset;

class RemoteController_terminateMember_result {
 public:

  RemoteController_terminateMember_result(const RemoteController_terminateMember_result&);
  RemoteController_terminateMember_result& operator=(const RemoteController_terminateMember_result&);
  RemoteController_terminateMember_result() : success(0) {
  }

  virtual ~RemoteController_terminateMember_result() throw();
  bool success;

  _RemoteController_terminateMember_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_terminateMember_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_terminateMember_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_terminateMember_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_terminateMember_presult__isset {
  _RemoteController_terminateMember_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_terminateMember_presult__isset;

class RemoteController_terminateMember_presult {
 public:


  virtual ~RemoteController_terminateMember_presult() throw();
  bool* success;

  _RemoteController_terminateMember_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_suspendMember_args__isset {
  _RemoteController_suspendMember_args__isset() : clusterId(false), memberId(false) {}
  bool clusterId :1;
  bool memberId :1;
} _RemoteController_suspendMember_args__isset;

class RemoteController_suspendMember_args {
 public:

  RemoteController_suspendMember_args(const RemoteController_suspendMember_args&);
  RemoteController_suspendMember_args& operator=(const RemoteController_suspendMember_args&);
  RemoteController_suspendMember_args() : clusterId(), memberId() {
  }

  virtual ~RemoteController_suspendMember_args() throw();
  std::string clusterId;
  std::string memberId;

  _RemoteController_suspendMember_args__isset __isset;

  void __set_clusterId(const std::string& val);

  void __set_memberId(const std::string& val);

  bool operator == (const RemoteController_suspendMember_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    if (!(memberId == rhs.memberId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_suspendMember_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_suspendMember_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_suspendMember_pargs {
 public:


  virtual ~RemoteController_suspendMember_pargs() throw();
  const std::string* clusterId;
  const std::string* memberId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_suspendMember_result__isset {
  _RemoteController_suspendMember_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_suspendMember_result__isset;

class RemoteController_suspendMember_result {
 public:

  RemoteController_suspendMember_result(const RemoteController_suspendMember_result&);
  RemoteController_suspendMember_result& operator=(const RemoteController_suspendMember_result&);
  RemoteController_suspendMember_result() : success(0) {
  }

  virtual ~RemoteController_suspendMember_result() throw();
  bool success;

  _RemoteController_suspendMember_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_suspendMember_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_suspendMember_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_suspendMember_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_suspendMember_presult__isset {
  _RemoteController_suspendMember_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_suspendMember_presult__isset;

class RemoteController_suspendMember_presult {
 public:


  virtual ~RemoteController_suspendMember_presult() throw();
  bool* success;

  _RemoteController_suspendMember_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_resumeMember_args__isset {
  _RemoteController_resumeMember_args__isset() : clusterId(false), memberId(false) {}
  bool clusterId :1;
  bool memberId :1;
} _RemoteController_resumeMember_args__isset;

class RemoteController_resumeMember_args {
 public:

  RemoteController_resumeMember_args(const RemoteController_resumeMember_args&);
  RemoteController_resumeMember_args& operator=(const RemoteController_resumeMember_args&);
  RemoteController_resumeMember_args() : clusterId(), memberId() {
  }

  virtual ~RemoteController_resumeMember_args() throw();
  std::string clusterId;
  std::string memberId;

  _RemoteController_resumeMember_args__isset __isset;

  void __set_clusterId(const std::string& val);

  void __set_memberId(const std::string& val);

  bool operator == (const RemoteController_resumeMember_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    if (!(memberId == rhs.memberId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_resumeMember_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_resumeMember_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_resumeMember_pargs {
 public:


  virtual ~RemoteController_resumeMember_pargs() throw();
  const std::string* clusterId;
  const std::string* memberId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_resumeMember_result__isset {
  _RemoteController_resumeMember_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_resumeMember_result__isset;

class RemoteController_resumeMember_result {
 public:

  RemoteController_resumeMember_result(const RemoteController_resumeMember_result&);
  RemoteController_resumeMember_result& operator=(const RemoteController_resumeMember_result&);
  RemoteController_resumeMember_result() : success(0) {
  }

  virtual ~RemoteController_resumeMember_result() throw();
  bool success;

  _RemoteController_resumeMember_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_resumeMember_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_resumeMember_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_resumeMember_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_resumeMember_presult__isset {
  _RemoteController_resumeMember_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_resumeMember_presult__isset;

class RemoteController_resumeMember_presult {
 public:


  virtual ~RemoteController_resumeMember_presult() throw();
  bool* success;

  _RemoteController_resumeMember_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_shutdownCluster_args__isset {
  _RemoteController_shutdownCluster_args__isset() : clusterId(false) {}
  bool clusterId :1;
} _RemoteController_shutdownCluster_args__isset;

class RemoteController_shutdownCluster_args {
 public:

  RemoteController_shutdownCluster_args(const RemoteController_shutdownCluster_args&);
  RemoteController_shutdownCluster_args& operator=(const RemoteController_shutdownCluster_args&);
  RemoteController_shutdownCluster_args() : clusterId() {
  }

  virtual ~RemoteController_shutdownCluster_args() throw();
  std::string clusterId;

  _RemoteController_shutdownCluster_args__isset __isset;

  void __set_clusterId(const std::string& val);

  bool operator == (const RemoteController_shutdownCluster_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_shutdownCluster_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_shutdownCluster_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_shutdownCluster_pargs {
 public:


  virtual ~RemoteController_shutdownCluster_pargs() throw();
  const std::string* clusterId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_shutdownCluster_result__isset {
  _RemoteController_shutdownCluster_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_shutdownCluster_result__isset;

class RemoteController_shutdownCluster_result {
 public:

  RemoteController_shutdownCluster_result(const RemoteController_shutdownCluster_result&);
  RemoteController_shutdownCluster_result& operator=(const RemoteController_shutdownCluster_result&);
  RemoteController_shutdownCluster_result() : success(0) {
  }

  virtual ~RemoteController_shutdownCluster_result() throw();
  bool success;

  _RemoteController_shutdownCluster_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_shutdownCluster_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_shutdownCluster_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_shutdownCluster_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_shutdownCluster_presult__isset {
  _RemoteController_shutdownCluster_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_shutdownCluster_presult__isset;

class RemoteController_shutdownCluster_presult {
 public:


  virtual ~RemoteController_shutdownCluster_presult() throw();
  bool* success;

  _RemoteController_shutdownCluster_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_terminateCluster_args__isset {
  _RemoteController_terminateCluster_args__isset() : clusterId(false) {}
  bool clusterId :1;
} _RemoteController_terminateCluster_args__isset;

class RemoteController_terminateCluster_args {
 public:

  RemoteController_terminateCluster_args(const RemoteController_terminateCluster_args&);
  RemoteController_terminateCluster_args& operator=(const RemoteController_terminateCluster_args&);
  RemoteController_terminateCluster_args() : clusterId() {
  }

  virtual ~RemoteController_terminateCluster_args() throw();
  std::string clusterId;

  _RemoteController_terminateCluster_args__isset __isset;

  void __set_clusterId(const std::string& val);

  bool operator == (const RemoteController_terminateCluster_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_terminateCluster_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_terminateCluster_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_terminateCluster_pargs {
 public:


  virtual ~RemoteController_terminateCluster_pargs() throw();
  const std::string* clusterId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_terminateCluster_result__isset {
  _RemoteController_terminateCluster_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_terminateCluster_result__isset;

class RemoteController_terminateCluster_result {
 public:

  RemoteController_terminateCluster_result(const RemoteController_terminateCluster_result&);
  RemoteController_terminateCluster_result& operator=(const RemoteController_terminateCluster_result&);
  RemoteController_terminateCluster_result() : success(0) {
  }

  virtual ~RemoteController_terminateCluster_result() throw();
  bool success;

  _RemoteController_terminateCluster_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const RemoteController_terminateCluster_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_terminateCluster_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_terminateCluster_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_terminateCluster_presult__isset {
  _RemoteController_terminateCluster_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_terminateCluster_presult__isset;

class RemoteController_terminateCluster_presult {
 public:


  virtual ~RemoteController_terminateCluster_presult() throw();
  bool* success;

  _RemoteController_terminateCluster_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_splitMemberFromCluster_args__isset {
  _RemoteController_splitMemberFromCluster_args__isset() : memberId(false) {}
  bool memberId :1;
} _RemoteController_splitMemberFromCluster_args__isset;

class RemoteController_splitMemberFromCluster_args {
 public:

  RemoteController_splitMemberFromCluster_args(const RemoteController_splitMemberFromCluster_args&);
  RemoteController_splitMemberFromCluster_args& operator=(const RemoteController_splitMemberFromCluster_args&);
  RemoteController_splitMemberFromCluster_args() : memberId() {
  }

  virtual ~RemoteController_splitMemberFromCluster_args() throw();
  std::string memberId;

  _RemoteController_splitMemberFromCluster_args__isset __isset;

  void __set_memberId(const std::string& val);

  bool operator == (const RemoteController_splitMemberFromCluster_args & rhs) const
  {
    if (!(memberId == rhs.memberId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_splitMemberFromCluster_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_splitMemberFromCluster_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_splitMemberFromCluster_pargs {
 public:


  virtual ~RemoteController_splitMemberFromCluster_pargs() throw();
  const std::string* memberId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_splitMemberFromCluster_result__isset {
  _RemoteController_splitMemberFromCluster_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_splitMemberFromCluster_result__isset;

class RemoteController_splitMemberFromCluster_result {
 public:

  RemoteController_splitMemberFromCluster_result(const RemoteController_splitMemberFromCluster_result&);
  RemoteController_splitMemberFromCluster_result& operator=(const RemoteController_splitMemberFromCluster_result&);
  RemoteController_splitMemberFromCluster_result() {
  }

  virtual ~RemoteController_splitMemberFromCluster_result() throw();
  Cluster success;

  _RemoteController_splitMemberFromCluster_result__isset __isset;

  void __set_success(const Cluster& val);

  bool operator == (const RemoteController_splitMemberFromCluster_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_splitMemberFromCluster_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_splitMemberFromCluster_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_splitMemberFromCluster_presult__isset {
  _RemoteController_splitMemberFromCluster_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_splitMemberFromCluster_presult__isset;

class RemoteController_splitMemberFromCluster_presult {
 public:


  virtual ~RemoteController_splitMemberFromCluster_presult() throw();
  Cluster* success;

  _RemoteController_splitMemberFromCluster_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_mergeMemberToCluster_args__isset {
  _RemoteController_mergeMemberToCluster_args__isset() : clusterId(false), memberId(false) {}
  bool clusterId :1;
  bool memberId :1;
} _RemoteController_mergeMemberToCluster_args__isset;

class RemoteController_mergeMemberToCluster_args {
 public:

  RemoteController_mergeMemberToCluster_args(const RemoteController_mergeMemberToCluster_args&);
  RemoteController_mergeMemberToCluster_args& operator=(const RemoteController_mergeMemberToCluster_args&);
  RemoteController_mergeMemberToCluster_args() : clusterId(), memberId() {
  }

  virtual ~RemoteController_mergeMemberToCluster_args() throw();
  std::string clusterId;
  std::string memberId;

  _RemoteController_mergeMemberToCluster_args__isset __isset;

  void __set_clusterId(const std::string& val);

  void __set_memberId(const std::string& val);

  bool operator == (const RemoteController_mergeMemberToCluster_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    if (!(memberId == rhs.memberId))
      return false;
    return true;
  }
  bool operator != (const RemoteController_mergeMemberToCluster_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_mergeMemberToCluster_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_mergeMemberToCluster_pargs {
 public:


  virtual ~RemoteController_mergeMemberToCluster_pargs() throw();
  const std::string* clusterId;
  const std::string* memberId;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_mergeMemberToCluster_result__isset {
  _RemoteController_mergeMemberToCluster_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_mergeMemberToCluster_result__isset;

class RemoteController_mergeMemberToCluster_result {
 public:

  RemoteController_mergeMemberToCluster_result(const RemoteController_mergeMemberToCluster_result&);
  RemoteController_mergeMemberToCluster_result& operator=(const RemoteController_mergeMemberToCluster_result&);
  RemoteController_mergeMemberToCluster_result() {
  }

  virtual ~RemoteController_mergeMemberToCluster_result() throw();
  Cluster success;

  _RemoteController_mergeMemberToCluster_result__isset __isset;

  void __set_success(const Cluster& val);

  bool operator == (const RemoteController_mergeMemberToCluster_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_mergeMemberToCluster_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_mergeMemberToCluster_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_mergeMemberToCluster_presult__isset {
  _RemoteController_mergeMemberToCluster_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_mergeMemberToCluster_presult__isset;

class RemoteController_mergeMemberToCluster_presult {
 public:


  virtual ~RemoteController_mergeMemberToCluster_presult() throw();
  Cluster* success;

  _RemoteController_mergeMemberToCluster_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RemoteController_executeOnController_args__isset {
  _RemoteController_executeOnController_args__isset() : clusterId(false), script(false), lang(false) {}
  bool clusterId :1;
  bool script :1;
  bool lang :1;
} _RemoteController_executeOnController_args__isset;

class RemoteController_executeOnController_args {
 public:

  RemoteController_executeOnController_args(const RemoteController_executeOnController_args&);
  RemoteController_executeOnController_args& operator=(const RemoteController_executeOnController_args&);
  RemoteController_executeOnController_args() : clusterId(), script(), lang((Lang::type)0) {
  }

  virtual ~RemoteController_executeOnController_args() throw();
  std::string clusterId;
  std::string script;
  Lang::type lang;

  _RemoteController_executeOnController_args__isset __isset;

  void __set_clusterId(const std::string& val);

  void __set_script(const std::string& val);

  void __set_lang(const Lang::type val);

  bool operator == (const RemoteController_executeOnController_args & rhs) const
  {
    if (!(clusterId == rhs.clusterId))
      return false;
    if (!(script == rhs.script))
      return false;
    if (!(lang == rhs.lang))
      return false;
    return true;
  }
  bool operator != (const RemoteController_executeOnController_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_executeOnController_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RemoteController_executeOnController_pargs {
 public:


  virtual ~RemoteController_executeOnController_pargs() throw();
  const std::string* clusterId;
  const std::string* script;
  const Lang::type* lang;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_executeOnController_result__isset {
  _RemoteController_executeOnController_result__isset() : success(false) {}
  bool success :1;
} _RemoteController_executeOnController_result__isset;

class RemoteController_executeOnController_result {
 public:

  RemoteController_executeOnController_result(const RemoteController_executeOnController_result&);
  RemoteController_executeOnController_result& operator=(const RemoteController_executeOnController_result&);
  RemoteController_executeOnController_result() {
  }

  virtual ~RemoteController_executeOnController_result() throw();
  Response success;

  _RemoteController_executeOnController_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const RemoteController_executeOnController_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RemoteController_executeOnController_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemoteController_executeOnController_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RemoteController_executeOnController_presult__isset {
  _RemoteController_executeOnController_presult__isset() : success(false) {}
  bool success :1;
} _RemoteController_executeOnController_presult__isset;

class RemoteController_executeOnController_presult {
 public:


  virtual ~RemoteController_executeOnController_presult() throw();
  Response* success;

  _RemoteController_executeOnController_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RemoteControllerClient : virtual public RemoteControllerIf {
 public:
  RemoteControllerClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RemoteControllerClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool ping();
  void send_ping();
  bool recv_ping();
  bool clean();
  void send_clean();
  bool recv_clean();
  bool exit();
  void send_exit();
  bool recv_exit();
  void createCluster(Cluster& _return, const std::string& hzVersion, const std::string& xmlconfig);
  void send_createCluster(const std::string& hzVersion, const std::string& xmlconfig);
  void recv_createCluster(Cluster& _return);
  void startMember(Member& _return, const std::string& clusterId);
  void send_startMember(const std::string& clusterId);
  void recv_startMember(Member& _return);
  bool shutdownMember(const std::string& clusterId, const std::string& memberId);
  void send_shutdownMember(const std::string& clusterId, const std::string& memberId);
  bool recv_shutdownMember();
  bool terminateMember(const std::string& clusterId, const std::string& memberId);
  void send_terminateMember(const std::string& clusterId, const std::string& memberId);
  bool recv_terminateMember();
  bool suspendMember(const std::string& clusterId, const std::string& memberId);
  void send_suspendMember(const std::string& clusterId, const std::string& memberId);
  bool recv_suspendMember();
  bool resumeMember(const std::string& clusterId, const std::string& memberId);
  void send_resumeMember(const std::string& clusterId, const std::string& memberId);
  bool recv_resumeMember();
  bool shutdownCluster(const std::string& clusterId);
  void send_shutdownCluster(const std::string& clusterId);
  bool recv_shutdownCluster();
  bool terminateCluster(const std::string& clusterId);
  void send_terminateCluster(const std::string& clusterId);
  bool recv_terminateCluster();
  void splitMemberFromCluster(Cluster& _return, const std::string& memberId);
  void send_splitMemberFromCluster(const std::string& memberId);
  void recv_splitMemberFromCluster(Cluster& _return);
  void mergeMemberToCluster(Cluster& _return, const std::string& clusterId, const std::string& memberId);
  void send_mergeMemberToCluster(const std::string& clusterId, const std::string& memberId);
  void recv_mergeMemberToCluster(Cluster& _return);
  void executeOnController(Response& _return, const std::string& clusterId, const std::string& script, const Lang::type lang);
  void send_executeOnController(const std::string& clusterId, const std::string& script, const Lang::type lang);
  void recv_executeOnController(Response& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RemoteControllerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<RemoteControllerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RemoteControllerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_clean(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_exit(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_createCluster(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_startMember(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdownMember(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_terminateMember(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_suspendMember(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_resumeMember(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdownCluster(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_terminateCluster(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_splitMemberFromCluster(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_mergeMemberToCluster(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_executeOnController(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RemoteControllerProcessor(::apache::thrift::stdcxx::shared_ptr<RemoteControllerIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &RemoteControllerProcessor::process_ping;
    processMap_["clean"] = &RemoteControllerProcessor::process_clean;
    processMap_["exit"] = &RemoteControllerProcessor::process_exit;
    processMap_["createCluster"] = &RemoteControllerProcessor::process_createCluster;
    processMap_["startMember"] = &RemoteControllerProcessor::process_startMember;
    processMap_["shutdownMember"] = &RemoteControllerProcessor::process_shutdownMember;
    processMap_["terminateMember"] = &RemoteControllerProcessor::process_terminateMember;
    processMap_["suspendMember"] = &RemoteControllerProcessor::process_suspendMember;
    processMap_["resumeMember"] = &RemoteControllerProcessor::process_resumeMember;
    processMap_["shutdownCluster"] = &RemoteControllerProcessor::process_shutdownCluster;
    processMap_["terminateCluster"] = &RemoteControllerProcessor::process_terminateCluster;
    processMap_["splitMemberFromCluster"] = &RemoteControllerProcessor::process_splitMemberFromCluster;
    processMap_["mergeMemberToCluster"] = &RemoteControllerProcessor::process_mergeMemberToCluster;
    processMap_["executeOnController"] = &RemoteControllerProcessor::process_executeOnController;
  }

  virtual ~RemoteControllerProcessor() {}
};

class RemoteControllerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RemoteControllerProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< RemoteControllerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< RemoteControllerIfFactory > handlerFactory_;
};

class RemoteControllerMultiface : virtual public RemoteControllerIf {
 public:
  RemoteControllerMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<RemoteControllerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RemoteControllerMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<RemoteControllerIf> > ifaces_;
  RemoteControllerMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<RemoteControllerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    return ifaces_[i]->ping();
  }

  bool clean() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->clean();
    }
    return ifaces_[i]->clean();
  }

  bool exit() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->exit();
    }
    return ifaces_[i]->exit();
  }

  void createCluster(Cluster& _return, const std::string& hzVersion, const std::string& xmlconfig) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->createCluster(_return, hzVersion, xmlconfig);
    }
    ifaces_[i]->createCluster(_return, hzVersion, xmlconfig);
    return;
  }

  void startMember(Member& _return, const std::string& clusterId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->startMember(_return, clusterId);
    }
    ifaces_[i]->startMember(_return, clusterId);
    return;
  }

  bool shutdownMember(const std::string& clusterId, const std::string& memberId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdownMember(clusterId, memberId);
    }
    return ifaces_[i]->shutdownMember(clusterId, memberId);
  }

  bool terminateMember(const std::string& clusterId, const std::string& memberId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->terminateMember(clusterId, memberId);
    }
    return ifaces_[i]->terminateMember(clusterId, memberId);
  }

  bool suspendMember(const std::string& clusterId, const std::string& memberId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->suspendMember(clusterId, memberId);
    }
    return ifaces_[i]->suspendMember(clusterId, memberId);
  }

  bool resumeMember(const std::string& clusterId, const std::string& memberId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->resumeMember(clusterId, memberId);
    }
    return ifaces_[i]->resumeMember(clusterId, memberId);
  }

  bool shutdownCluster(const std::string& clusterId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdownCluster(clusterId);
    }
    return ifaces_[i]->shutdownCluster(clusterId);
  }

  bool terminateCluster(const std::string& clusterId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->terminateCluster(clusterId);
    }
    return ifaces_[i]->terminateCluster(clusterId);
  }

  void splitMemberFromCluster(Cluster& _return, const std::string& memberId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->splitMemberFromCluster(_return, memberId);
    }
    ifaces_[i]->splitMemberFromCluster(_return, memberId);
    return;
  }

  void mergeMemberToCluster(Cluster& _return, const std::string& clusterId, const std::string& memberId) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->mergeMemberToCluster(_return, clusterId, memberId);
    }
    ifaces_[i]->mergeMemberToCluster(_return, clusterId, memberId);
    return;
  }

  void executeOnController(Response& _return, const std::string& clusterId, const std::string& script, const Lang::type lang) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->executeOnController(_return, clusterId, script, lang);
    }
    ifaces_[i]->executeOnController(_return, clusterId, script, lang);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class RemoteControllerConcurrentClient : virtual public RemoteControllerIf {
 public:
  RemoteControllerConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RemoteControllerConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool ping();
  int32_t send_ping();
  bool recv_ping(const int32_t seqid);
  bool clean();
  int32_t send_clean();
  bool recv_clean(const int32_t seqid);
  bool exit();
  int32_t send_exit();
  bool recv_exit(const int32_t seqid);
  void createCluster(Cluster& _return, const std::string& hzVersion, const std::string& xmlconfig);
  int32_t send_createCluster(const std::string& hzVersion, const std::string& xmlconfig);
  void recv_createCluster(Cluster& _return, const int32_t seqid);
  void startMember(Member& _return, const std::string& clusterId);
  int32_t send_startMember(const std::string& clusterId);
  void recv_startMember(Member& _return, const int32_t seqid);
  bool shutdownMember(const std::string& clusterId, const std::string& memberId);
  int32_t send_shutdownMember(const std::string& clusterId, const std::string& memberId);
  bool recv_shutdownMember(const int32_t seqid);
  bool terminateMember(const std::string& clusterId, const std::string& memberId);
  int32_t send_terminateMember(const std::string& clusterId, const std::string& memberId);
  bool recv_terminateMember(const int32_t seqid);
  bool suspendMember(const std::string& clusterId, const std::string& memberId);
  int32_t send_suspendMember(const std::string& clusterId, const std::string& memberId);
  bool recv_suspendMember(const int32_t seqid);
  bool resumeMember(const std::string& clusterId, const std::string& memberId);
  int32_t send_resumeMember(const std::string& clusterId, const std::string& memberId);
  bool recv_resumeMember(const int32_t seqid);
  bool shutdownCluster(const std::string& clusterId);
  int32_t send_shutdownCluster(const std::string& clusterId);
  bool recv_shutdownCluster(const int32_t seqid);
  bool terminateCluster(const std::string& clusterId);
  int32_t send_terminateCluster(const std::string& clusterId);
  bool recv_terminateCluster(const int32_t seqid);
  void splitMemberFromCluster(Cluster& _return, const std::string& memberId);
  int32_t send_splitMemberFromCluster(const std::string& memberId);
  void recv_splitMemberFromCluster(Cluster& _return, const int32_t seqid);
  void mergeMemberToCluster(Cluster& _return, const std::string& clusterId, const std::string& memberId);
  int32_t send_mergeMemberToCluster(const std::string& clusterId, const std::string& memberId);
  void recv_mergeMemberToCluster(Cluster& _return, const int32_t seqid);
  void executeOnController(Response& _return, const std::string& clusterId, const std::string& script, const Lang::type lang);
  int32_t send_executeOnController(const std::string& clusterId, const std::string& script, const Lang::type lang);
  void recv_executeOnController(Response& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
