/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "remotecontroller_constants.h"



const remotecontrollerConstants g_remotecontroller_constants;

remotecontrollerConstants::remotecontrollerConstants() {
}



