name: Coverage Report

inputs:
  GH_TOKEN:
    required: true
  BOOST_VERSION:
    required: true
  THRIFT_VERSION:
    required: true
  RUN_TESTS:
    required: true
  HAZELCAST_ENTERPRISE_KEY:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  HZ_TEST_AWS_INSTANCE_PRIVATE_IP:
    required: true

env:
  # Not possible to set this as a default
  # https://github.com/orgs/community/discussions/46670
  shell: bash

runs:
  using: composite
  steps:
    - uses: ./.github/actions/ubuntu-x86_64
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        BOOST_VERSION: ${{ inputs.BOOST_VERSION }}
        THRIFT_VERSION: ${{ inputs.THRIFT_VERSION }}
        WARN_AS_ERR: OFF
        BUILD_TYPE: Debug
        SHARED_LIBS_TOGGLE: ON
        OPENSSL_TOGGLE: ON
        RUN_TESTS: ${{ inputs.RUN_TESTS }}
        HAZELCAST_ENTERPRISE_KEY: ${{ inputs.HAZELCAST_ENTERPRISE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        HZ_TEST_AWS_INSTANCE_PRIVATE_IP: ${{ inputs.HZ_TEST_AWS_INSTANCE_PRIVATE_IP }}

    - name: Install Necessary Packages
      shell: ${{ env.shell }}
      run: |
        sudo apt-get install -y gcovr

    - name: Collect coverage info
      shell: ${{ env.shell }}
      run: |
        # collect and list coverage info
        lcov --capture --directory . --no-external -o coverage.info \
              --include "`pwd`/hazelcast/*" --exclude "`pwd`/hazelcast/test/*"
        lcov --list coverage.info
        # generate HTML views
        genhtml coverage.info --output-directory=coverage-html-reports

    - name: Upload HTML views as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: |
          coverage.info
          coverage-html-reports
