name: Build & Test - Unix

inputs:
  GH_TOKEN:
    required: true
  BOOST_VERSION:
    required: true
  THRIFT_VERSION:
    required: true
  BUILD_TYPE:
    required: true
  SHARED_LIBS_TOGGLE:
    required: true
  OPENSSL_TOGGLE:
    required: true
  RUN_TESTS:
    required: true
  HAZELCAST_ENTERPRISE_KEY:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  HZ_TEST_AWS_INSTANCE_PRIVATE_IP:
    required: true

runs:
  using: composite
  steps:
    - name: Download hazelcast-enterprise-tests.jar
      shell: bash
      run: |
        gh api "/repos/hazelcast/private-test-artifacts/contents/certs.jar?ref=data" -H "Accept: application/vnd.github.raw" > hazelcast-enterprise-${{ env.HZ_VERSION }}-tests.jar
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Build & Install
      env:
        BUILD_DIR: build
        INSTALL: ON
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      shell: bash
      run: |
        ./scripts/build-unix.sh                                          \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/destination   \
            -DBUILD_SHARED_LIBS=${{ inputs.SHARED_LIBS_TOGGLE }}         \
            -DWITH_OPENSSL=${{ inputs.OPENSSL_TOGGLE }}                  \
            -DBUILD_TESTS=ON                                             \
            -DBUILD_EXAMPLES=OFF

    - name: Test
      if: ${{ inputs.run_tests == 'true' }}
      env:
        BUILD_DIR: build
        HAZELCAST_ENTERPRISE_KEY: ${{ inputs.HAZELCAST_ENTERPRISE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        HZ_TEST_AWS_INSTANCE_PRIVATE_IP: ${{ inputs.HZ_TEST_AWS_INSTANCE_PRIVATE_IP }}
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      shell: bash
      run: |
        ./scripts/test-unix.sh
