name: Build&Test PR
on: 
  pull_request:

  
jobs:
  test-membership-actor:
    name: Test Hazelcast Membership with github.actor
    runs-on: ubuntu-latest
    outputs:
      is-hazelcast: ${{ steps.test-membership.outputs.check-result }}

    steps:
      - name: Test
        id: test-membership
        uses: hazelcast/hazelcast-tpm/membership@main
        with:
          member-name: ${{ github.actor }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Report
        run: echo "check-result = ${{ steps.test-membership.outputs.check-result }}"

  test-membership-triggering-actor:
    name: Test Hazelcast Membership with github.triggering_actor
    runs-on: ubuntu-latest
    outputs:
      is-hazelcast: ${{ steps.test-membership.outputs.check-result }}

    steps:
      - name: Test
        id: test-membership
        uses: hazelcast/hazelcast-tpm/membership@main
        with:
          member-name: ${{ github.triggering_actor }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Report
        run: echo "check-result = ${{ steps.test-membership.outputs.check-result }}"
