name: Get shared libs

on:
  workflow_call:
    outputs:
      shared-libs:
        value: ${{ jobs.get-shared-libs.outputs.shared-libs }}

jobs:
  get-shared-libs:
    runs-on: ubuntu-latest
    outputs:
      shared-libs: "[{ toggle: OFF, name: Static}, { toggle: ON, name: Shared}]"
    steps:
      - run: exit 0
