name: Git Bisect Test
on: 

  # automatic on every pull request
  pull_request:

env:
  boost_version: 1.78.0
  boost_archive_name: 'boost_1_78_0.tar.gz'
  boost_folder_name: 'boost_1_78_0'
  boost_include_folder: 'C:\Boost\include\boost-1_78'
  boost_url: 'https://archives.boost.io/release/1.78.0/source/boost_1_78_0.tar.gz'
  thrift_version: 0.13.0
  run_tests: false
  
jobs:
  # get
  get-refs:
    name: Get Refs
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get-refs.outputs.ref }}
      merged-ref: ${{ steps.get-refs.outputs.merged-ref }}

    steps:
      - name: Get Refs
        id: get-refs
        shell: bash
        run: |
          echo "EVENT: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "PR_NUMBER: ${{ inputs.pr_number }}"
            echo "PR_COMMIT: ${{ inputs.pr_commit }}"
            echo "ref=refs/pull/${{ inputs.pr_number }}/merge" >> $GITHUB_OUTPUT
            echo "merged-ref=${{ inputs.pr_commit }}" >> $GITHUB_OUTPUT
          else
            echo "PR_NUMBER: ${{ github.event.pull_request.number }}"
            echo "ref=refs/pull/${{ github.event.pull_request.number }}/merge" >> $GITHUB_OUTPUT
            echo "merged-ref=''" >> $GITHUB_OUTPUT
          fi

  Ubuntu-x86_64:
    needs: get-refs
    strategy:
      fail-fast: false
      matrix:

        build_type:
          - type: Debug
            warn_as_err: ON

        shared_libs:
          - toggle: OFF
            name: Static

        with_openssl:
          - toggle: ON
            name: SSL

    runs-on: ubuntu-latest

    name: ubuntu-x64-(${{ matrix.build_type.type }}, ${{ matrix.shared_libs.name }}, ${{ matrix.with_openssl.name }})
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.get-refs.outputs.ref }}
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: 'hazelcast/hazelcast-mono'
          ref: '0164d113f832d53a897bc72569c284a17272cde0'
          path: 'hazelcast-repo'
          token: ${{ secrets.GH_TOKEN }}

      - uses: ./.github/actions/build-test/ubuntu-x86_64
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BOOST_VERSION: ${{ env.boost_version }}
          THRIFT_VERSION: ${{ env.thrift_version }}
          WARN_AS_ERR: ${{ matrix.build_type.warn_as_err }}
          BUILD_TYPE: ${{ matrix.build_type.type }}
          SHARED_LIBS_TOGGLE: ${{ matrix.shared_libs.toggle }}
          OPENSSL_TOGGLE: ${{ matrix.with_openssl.toggle }}
          RUN_TESTS: ${{ env.run_tests }}
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HZ_TEST_AWS_INSTANCE_PRIVATE_IP: ${{ secrets.HZ_TEST_AWS_INSTANCE_PRIVATE_IP }}
